pipeline:
  name: use sonarqube step to scan
  identifier: use_sonarqube_step_to_scan
  projectIdentifier: SonarQube_Test_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Mission11_Alternative_Repo
        build: <+input>
  stages:
    - stage:
        name: SQ Stage
        identifier: SQ_Stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: echo step
                  identifier: echo_step
                  spec:
                    shell: Sh
                    command: echo "Start"
              - step:
                  type: Sonarqube
                  name: Sonarqube scan code
                  identifier: Sonarqube_scan_code
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                    connectorRef: account.harnessImage
                    auth:
                      access_token: <+secrets.sonartoken>
                      domain: http://35.206.188.23:9000/
                      ssl: true
